### ISSUE TITLE
Error accessing `notebook.metadata.language_info.file_extension`

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter/jupyter-sphinx#108]
Copied from  ExecutableBookProject/MyST-NB#63

 `jupyter-sphinx` expects the presence of `notebook.metadata.language_info.file_extension` here:
https://github.com/jupyter/jupyter-sphinx/blob/970097e01c1b7af04372be202aed572de68d2d20/jupyter_sphinx/execute.py#L259

However, it appears that this is not actual a *necessary* attribute of the notebook metadata, as exampled by the working notebook below:

```json
{
 "nbformat": 4,
 "nbformat_minor": 2,
 "metadata": {
  "language_info": {
   "name": "python",
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   }
  },
  "orig_nbformat": 2,
  "file_extension": ".py",
  "mimetype": "text/x-python",
  "name": "python",
  "npconvert_exporter": "python",
  "pygments_lexer": "ipython3",
  "version": 3
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(use/api)=\n",
    "\n",
    "# Python API"
   ]
  }
 ]
}
```

Note, the notebook was initially created by VS Code:

```yaml
Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.
Version: 2020.2.64397
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python 
```

perhaps just have `notebook.metadata.language_info.get("file_extension", ".py")`
