### ISSUE TITLE
impact output background if dark mode activated

### ISSUE THREAD

**Issue by LuisBL** [jupyter/jupyter-sphinx#218]
Hello, 
First things first: Thank you for this fantastic module.

I use jupyter-sphinx with furo theme. When dark mode is activated doesn't look good

![image](https://user-images.githubusercontent.com/694774/213997888-f40d9d25-9f3d-48e2-87bf-0854be314056.png)

What is the recommended way to go ?

**Comment by sjrowlinson** [comment]
I encountered a similar issue recently whilst using the pydata-sphinx-theme. Adding the following overrides:

```css
html[data-theme="dark"] .bd-content div.cell_output .text_html,
html[data-theme="dark"] .bd-content div.cell_output img {
    background-color: var(--pst-color-background);
    color: var(--pst-color-text-base);
}
```

to my custom CSS file (in my case, in `docs/source/_static/<projectname>.css`) seemed to work for me. Note that this will set the background color of these cell outputs to the corresponding dark theme background, but you can set it to the color of literal blocks with this instead:

```css
background-color: var(--pst-color-surface);
```
