### ISSUE TITLE
CSS rule applied on wrong elements

### ISSUE THREAD

**Issue by martinRenou** [jupyter/jupyter-sphinx#96]
The following CSS rule:
```css
div.jupyter_container * {
    padding: 0;
    margin: 0;
}
```

is applied on the `LeafletJS` popups and controls on the following pages:
- https://ipyleaflet.readthedocs.io/en/latest/api_reference/popup.html (click on the marker to see the Popup)
- https://ipyleaflet.readthedocs.io/en/latest/api_reference/layers_control.html (Click on the button on top right of the Map to see it)

It breaks their visual aspect. As a comparison, here is what the popup should look like:
![popup](https://user-images.githubusercontent.com/21197331/73553973-27d92680-444b-11ea-888b-8ae1593a1af4.png)

I don't know what this rule should be instead, maybe:
```css
// Without the star
div.jupyter_container {
    padding: 0;
    margin: 0;
}
```
is enough.
